# Generated by Django 4.1.7 on 2023-03-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_alter_blog_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloguser',
            old_name='name',
            new_name='dysplay_name',
        ),
    ]
