# Generated by Django 4.1.7 on 2023-03-07 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_rename_name_bloguser_dysplay_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloguser',
            old_name='dysplay_name',
            new_name='display_name',
        ),
        migrations.AddField(
            model_name='bloguser',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
