# Generated by Django 4.1.7 on 2023-03-07 14:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0006_remove_bloguser_date_registered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
    ]
