# Generated by Django 4.1.7 on 2023-03-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0007_alter_bloguser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='display_name',
            field=models.CharField(max_length=255),
        ),
    ]
