# Generated by Django 4.1.7 on 2023-03-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0009_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='app_blog/assets/default_blog_image.jpg', upload_to='blog_pictures/'),
        ),
    ]
