# Generated by Django 4.1.7 on 2023-03-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0011_alter_bloguser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='app_blog/assets/default_profile_picture.jpg', upload_to='profile_pictures/'),
        ),
    ]
