# Generated by Django 4.1.7 on 2023-03-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0013_alter_blog_description_alter_blog_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='app_blog/assets/default_blog_image.jpg', null=True, upload_to='blog_pictures/'),
        ),
    ]
