# Generated by Django 4.1.7 on 2023-03-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0014_alter_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField(max_length=3000)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='url',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='url',
        ),
        migrations.RemoveField(
            model_name='post',
            name='state',
        ),
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
    ]
