# Generated by Django 4.1.7 on 2023-03-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0016_alter_blog_author_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
