# Generated by Django 4.1.7 on 2023-03-19 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0017_alter_avatar_profile_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogUser',
        ),
    ]
